id: P4CAEC514
initial_creation_type: ocr
source_metadata:
  volumes:
    0ed87d68125b47c283777b5665db43b2:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: འཕགས་པ་སཱ་ལུ་ལྗང་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1498
      volume_number: 65
